name: test
on: push
jobs : 
  print-hello:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: theshoklofty
          password: dckr_pat_-rGKlNY9deFEB3BeuzMDiiJ7_Xc
      - 
        name: npm install
        run: npm ci
      - 
        name: Build application
        run: npm run build
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - 
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: theshoklofty/docker-and-k8s:latest